:: To add a level, add the name of the .json file (without the extension) to the list of levels, make sure there is not an space after the ^. The ^ acts as a separator.
@echo off
py export_levels.py^
 stereomadness^
 backontrack^
 polargeist^
 dryout^
 baseafterbase^
 cantletgo^
 jumper^
 timemachine^
 cycles^
 xstep^
 clutterfunk^
 theoryofeverything^
 electromanadventures^
 clubstep^
 electrodynamix^
 hexagonforce^
 blastprocessing^
 theoryofeverything2^
 sonar^
 leveleasy^
 dorabaebasic7^
 anubis^
 scarletsurge^
 kappaclysm^
 funnygameholiday^
 revolution^
 fireaura_sumsar^
 tetrix^
 fireaura_tig^
 tig_oglevel^
 chaozfantasy_tig^
 payload^
 beastmode^
 machina^
 years^
 autocycles^
 retray^
 invisontrack^
 dorabaebasic^
 dorabaebasic2^
 dorabaebasic4^
 goldenclub^
 squareadv^
 selectpaymenttype^
 storymadness^
 groundtospace^
 one^
 dynamicontrack^
 iceland^
 ultimatedestruction^
 pyrophoric^
 cantletgov2^
 f^
 thenightmare^
 demonjumper^
 rose^
 problematic^
 deathmoon^
 acropolis^
 kaleidoscopic^
 everyend^
 test^
 test2^
 endless
pause